export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRINT_BILL = "PRINT_BILL";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const CREATE_ORDER_NUMBER = "CREATE_ORDER_NUMBER";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
